//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("URAL.FunctionalTests")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0+ad259f1b39c9c4a58f9c5e470f17586da01b89ab")]
[assembly: System.Reflection.AssemblyProductAttribute("URAL.FunctionalTests")]
[assembly: System.Reflection.AssemblyTitleAttribute("URAL.FunctionalTests")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
[assembly: CollectionBehavior(DisableTestParallelization = true)]

// Создано классом WriteCodeFragment MSBuild.

